name: Standard build deploy workflow for Kotlin Lambda GraalVM example

on:
  workflow_call:
    inputs:
      target_account:
        required: true
        type: string

env:
  # Supply target AWS account here
  DEPLOY_TARGET_ACCOUNT: ${{ inputs.target_account }}

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    name: Kotlin GraalVM deployment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Build with Maven
        run: mvn clean install --file software/products/pom.xml

#      - name: DEPLOY synthesize & deploy
#        run: |
#          cd ${GITHUB_WORKSPACE}/infrastructure
#          npm install
#          npm run build
#          npx cdk deploy -vv --require-approval never Kotlin-Lambda-GraalVM-example